### PR TITLE
feat: Application audio capture

### PR DESCRIPTION
**Pull request by sonicv6**
Allows users to exclusively capture the audio of the recorded game.

### CODE REVIEW

**Comment by sonicv6** [comment]
Closes #130

**Comment by lulzsun** [comment]
This currently works great and as intended, but I'm not sure if this closes #130 until we implement more options to allow to select additional applications and audio inputs (microphone).

Would it be okay to merge this as is anyways? Since this might be a basic feature that some may want to use until we can build a fully featured system for multiple input selection.

**Comment by sonicv6** [comment]
This includes some backend stuff for those options I just haven't done the frontend, I feel like creating a selector for running applications is a kind of awkward thing to do in React and was going to hand that back to Forms instead but didn't necessarily want to create even more reliance on Windows (although I think it's safe to assume 99% of users are probably on Windows)

**Comment by lulzsun** [comment]
Got it, then I think we can just merge this and handle the frontend controls in another pull request when we figure that out. I think we should also leave #130 open until then as well.

**Pull request merged**
