### PR TITLE
Added League Of Legends stats to Session card

### PR DESCRIPTION
**Pull request by Segergren**
Part of #108. Requested by @byotta
image

### CODE REVIEW

**Comment by lulzsun** [comment]
Looks good, but I feel like we should include the champion icon and the victory/loss label before I merge this.

Are we able to pass that information to video metadata as well?

**Comment by Segergren** [comment]
> Looks good, but I feel like we should include the champion icon and the victory/loss label before I merge this.
> 
> Are we able to pass that information to video metadata as well?

The champion icon is possible for sure 👍 I’ll check if victory/loss is possible :)

**Comment by Segergren** [comment]
Added the champion and win/loss indicator
image

**Comment by lulzsun** [comment]
Thanks! I went ahead and adjusted the design a little bit, here is how it looks now:
image

I think it is ready for merge now, thanks again for your time and work!

**Pull request merged**
