### PR TITLE
fix: Devices given the wrong source id

### PR DESCRIPTION
**Pull request by sonicv6**

### CODE REVIEW

**Comment by Segergren** [comment]
Now the in-game audio works but not the microphone

**Comment by sonicv6** [comment]
Closes #254

**Comment by Segergren** [comment]
Update: Works as expected. I had **Exclusively capture game audio** turned on...

**Review by lulzsun — APPROVED** [review]
Looks good, thanks for the fix.

**Comment by sonicv6** [comment]
Only seems fair, I broke it haha

**Pull request merged**
