### PR TITLE
feat: Bookmark KeyboardHook (F8)

### PR DESCRIPTION
**Pull request by Segergren**
You can now add bookmarks with the F8-key while in game.

### CODE REVIEW

**Comment by Segergren** [comment]
I want to change the bookmark sound to the old Plays sound, but I have issues trying to retrieve it.

**Comment by lulzsun** [comment]
I see you have created a `KeyboardHookService.cs` when we already have `HotkeyService.cs`. Is there an issue with HotkeyService? Or did you happen to not know it about?

We should either keep one or the other, or merge them together because they are essentially the same thing.

**Comment by Segergren** [comment]
Had no idea, how did I miss that 😁.
I'll check it out.

**Comment by Segergren** [comment]
Done! @lulzsun

**Review by lulzsun — APPROVED** [review]
Everything looks good, it could use some refactoring (merging the two key hook services into one) and coding style cleanup. But we can take care of that later. 

I have not personally tested the functionality myself, but everything checks out so I'll give it the approval.

Thanks for the great work! 😁

**Pull request merged**
