### PR TITLE
IMPR: Makes the autodetect not hook on the EasyAntiCheat-window.

### PR DESCRIPTION
**Pull request by Segergren**
Automatically reject EAC-windows. This allows the real game to be autodetected.
This makes it possible for some EAC-applications to use GameCapture instead of DisplayCapture, for example [Squad](https://store.steampowered.com/app/393380/Squad/)

### CODE REVIEW

**Comment by Segergren** [comment]
This might be related to issue #39 .

**Comment by lulzsun** [comment]
Yep, this is related to #39. We already have a slight implementation of this in BaseRecorder.cs (#40) to handle most splash screen windows.

The issue with this is that the EAC window handle name that you are checking for is not guaranteed to match other games. I noticed for the game Marauders, they use an unusual name for the EAC window handle. Which does not use "EACLauncherWnd" but instead "SDL_app"

**Comment by sonicv6** [comment]
I was going to suggest we create a file with blacklisted class/window names and load from it that way adding new ones is very simple

**Comment by Segergren** [comment]
Okay. @lulzsun Do you want to merge the PR or not? It should at least help improve capturing for some of the EAC games.

**Comment by lulzsun** [comment]
I don't think I'll be merging this as it currently is. I think we should either go by @sonicv6's suggestion or extend the current implementation in BaseRecorder.cs like so:
```diff
@@ -27,7 +27,7 @@ public abstract class BaseRecorder {
                // This detection is very primative and only covers specific cases, in the future we should find another way
                // to approach this issue. (possibily fetch to see if the window size ratio is not standard?)
-               var className = GetClassName(handle);
+               var className = GetClassName(handle).Replace(" ", "").ToLower();
-               if (className.Replace(" ", "").ToLower().Contains("splashscreen")) throw new Exception($"Window handle is a possible splash screen [{className}]");
+               if (className.Contains("splashscreen") || className.Equals("eaclauncherwnd")) throw new Exception($"Window handle is a possible splash screen [{className}]");
            }
```

This should do the same thing that you were initially trying to do. I think we should keep it simple and just reuse this part of the code instead of trying to handle the same issue elsewhere. We can decide on a proper implementation later.

**Comment by lulzsun** [comment]
Closing this since #61 took care of it.

**Pull request closed without merging**
